name = "OutlierDetection"
uuid = "262411bb-c475-4342-ba9e-03b8c0183ca6"
authors = ["David Muhr <muhrdavid+github@gmail.com> and contributors"]
version = "0.3.4"

[deps]
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
OutlierDetectionInterface = "1722ece6-f894-4ffc-b6be-6ca1174e2011"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
MLJBase = "0.21"
OutlierDetectionInterface = "~0.1.8"
SpecialFunctions = "1, 2"
julia = "^1.6"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Combinatorics"]
