name = "OutlierDetection"
uuid = "262411bb-c475-4342-ba9e-03b8c0183ca6"
authors = ["David Muhr <muhrdavid+github@gmail.com> and contributors"]
version = "0.1.1"

[deps]
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
OutlierDetectionInterface = "1722ece6-f894-4ffc-b6be-6ca1174e2011"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"
MLJModelInterface = "1.2"
MLJBase = "0.18"
OutlierDetectionInterface = "0.1"
SpecialFunctions = "1.0 - 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
