contact_links:
  - name: "\U0001F4AC All other questions and general chat"
    url: https://julialang.slack.com/archives/C02EXTD7WGG
    about: Chat with the community on Julia's Slack #outlierdetection
